//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expensess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int Id { get; set; }
        public int Food { get; set; }
        public Nullable<int> Education { get; set; }
        public Nullable<int> Health { get; set; }
        public Nullable<int> Travel { get; set; }
        public Nullable<int> Others { get; set; }
    }
}
